name = 'LCARS-NG'
license = 'GPL3'
licenselink = 'https://github.com/bertulli/hugo-lcars-ng/COPYING'
description = 'A Hugo theme inspired by Star Trek LCARS (Â© CBS Television Studios)'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/bertulli/hugo-lcars-ng'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Alessandro Bertulli'
  homepage = 'https://www.ensignsblog.net'
