baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'hugo-lcars-ng'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name =  "Home"
url =  ""
weight =  1
[[menu.main]]
name =  "About"
url =  "about/"
weight =  2
[[menu.main]]
name =  "Categories"
url =  "categories/"
weight =  3
[[menu.main]]
name =  "Tags"
url =  "tags/"
weight =  4
[[menu.main]]
name =  "Subscribe"
url =  "index.xml"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
